#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker
- name: Update system
  apt: "*"
  state: latest

- name: Install docker
  apt: docker.io
  state: latest

- name: Add users inside Docker Group
  user:
    name: "{{item}}"
    groups: docker
    append: yes
  loop: "{{docker_users}}"

- name: Restart docker
  service:
    name: docker
    state: restarted

- name: Register Docker version
  command: docker --version

- name: Show running containers
  command: docker ps
